# Password4j Configuration

# Argon2 settings
hash.argon2.memory=15360
hash.argon2.iterations=2
hash.argon2.length=32
hash.argon2.parallelism=1
hash.argon2.type=id
hash.argon2.version=19

# Global salt settings
global.salt.length=64

# Recommended hash function (can be ARGON2, BCRYPT, PBKDF2, SCRYPT)
hash.default=ARGON2